### ISSUE TITLE
[FEATURE] ClubSchedule Api 설계

### ISSUE THREAD

**Issue by goalSetter09** [IT-Cotato/9th-Squadus-BE#6]
## Description for development features
ClubSchedule Api 설계
## To-do  
- [ ] 소셜 로그인을 통한 jwt 발급 및 관리 기능 개발
- [ ] club schedule 관련 api 명세서 작성
- [ ] club schedule api 개발

## ETC
https://dnfldpden.atlassian.net/browse/JSGJ-74
